version: '3.9'

services:
  memes_service:
    container_name: memes_api
    build:
      dockerfile: docker/Dockerfile
      context: ./memes_service
      target: development
    ports:
      - "8001:8000"
    restart: unless-stopped
    volumes:
      - ./memes_service:/app

  memes_db:
    container_name: memes_postgres
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - ./memes_service/.env
    volumes:
      - memes_postgres_data:/var/lib/postgresql/data

  media_files_service:
    container_name: media_files_api
    build:
      dockerfile: docker/Dockerfile
      context: ./media_files_service
      target: development
    ports:
      - "8002:8000"
    restart: unless-stopped
    volumes:
      - ./media_files_service:/app


volumes:
  memes_postgres_data:
