"""Add image url to meme

Revision ID: 50dab0c8e955
Revises: a764d85d3949
Create Date: 2024-07-21 08:50:41.490068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50dab0c8e955'
down_revision: Union[str, None] = 'a764d85d3949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meme', 'image_url')
    # ### end Alembic commands ###
